### ISSUE TITLE
Implementation Query 

### ISSUE THREAD

**Issue by bhaveshhptl** [sunny06a/Resume-Screening#1]
Does this project work for resumes of different formats or only of the format of the dataset?

**Comment by sunny06a** [comment]
It works on any format till it can extract text from it

**Comment by bhaveshhptl** [comment]
I just cloned your repo and ran the code. It was not accurate. Was it the same in your case? How did you improve accuracy? Please help it's little urgent. I asked in context of accuracy

**Comment by sunny06a** [comment]
the accuracy i achieved was 84% and i tried many resume and it working fine, it would be helpful if u can share more details about the problem, if u are facing any error make sure abut the python version you are using is similar to mine.

**Comment by bhaveshhptl** [comment]
Can we connect somewhere else like Discord? I have lot of silly doubts.
Did you manually train the notebooks before testing? And the resumes for which it worked fine , I wanted to ask did you use the ones in the dataset or resumes of any format?

**Comment by sunny06a** [comment]
sunny03744, i used mine resume(latex format) to test

**Comment by bhaveshhptl** [comment]
I sent you the request. Thanks brother.

**Comment by bhaveshhptl** [comment]
Hi sunny , sorry for the delay. Please check once
